#!/bin/bash

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  🧠 НЕЙРО-ТАМАГОЧИ С МОЗГОВЫМИ ВОЛНАМИ                  ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "📦 Структура проекта:"
echo ""
echo "brainwave_project/"
echo "├── brainwave_core/          # Библиотека мозговых волн"
echo "│   ├── brainwaves.rs         # 5 типов волн + 8 состояний"
echo "│   ├── wave_network.rs       # Нейросеть с модуляцией"
echo "│   └── lib.rs"
echo "├── brainwave_tamagotchi/    # TUI приложение"
echo "│   └── main.rs               # Интерактивный тамагочи"
echo "└── README.md"
echo ""
echo "🌊 Мозговые волны:"
echo "   😴 Delta  (0.5-4 Hz)   - Глубокий сон"
echo "   🧘 Theta  (4-8 Hz)     - Медитация, творчество"
echo "   😌 Alpha  (8-13 Hz)    - Расслабление"
echo "   🤔 Beta   (13-30 Hz)   - Концентрация"
echo "   💡 Gamma  (30-100 Hz)  - Высшее сознание"
echo ""
echo "🎮 Управление:"
echo "   F - Покормить 🍎"
echo "   P - Поиграть 🎮"
echo "   S - Позаниматься 📚"
echo "   Z - Спать/Проснуться 😴"
echo "   Q - Выход"
echo ""
echo "🚀 Запуск:"
echo "   cd /root/brainwave_project"
echo "   cargo run --release -p brainwave_tamagotchi"
echo ""
echo "✨ Готово! Старые проекты удалены."
